name: Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código-fonte
      uses: actions/checkout@v2

    - name: Configurar o ambiente Java
      uses: actions/setup-java@v2.4.0
      with:
        java-version: '17'

    - name: Configurar o ambiente Kotlin
      uses: actions/setup-kotlin@v1

    - name: Executar os testes
      run: |
        cd post-microsservice && ./gradlew test
