name: Pipeline de Merge

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Roda os Testes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configurar o ambiente Java
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Fazer o teste
        run: |
          cd post-microsservice && ./gradlew test

  build:
    name: Executa um processo de build
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Login no Docker registry
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Construir a imagem Docker
        run: docker-compose build -t "ghcr.io/lukerops/ufes-posts-microservice:latest" -f docker-compose.yml .

      - name: Listar imagens Docker
        run: docker images

      - name: Executar o contêiner Docker
        run: docker run "ghcr.io/lukerops/ufes-posts-microservice:latest"

      - name: Publicar a imagem Docker
        run: docker push "ghcr.io/lukerops/ufes-posts-microservice:latest"
